trigger: none

resources:
  pipelines:
    - pipeline: platformCD
      source: platform-dev-cd
      trigger:
        branches:
          include:
            - dev

variables:
  - group: variables

stages:
- stage: DatabricksDeploy
  displayName: Deploy Databricks Workspace (PROD)
  jobs:
  - deployment: DeployDatabricks
    environment: dev
    variables:
      environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
            - download: platformCD
              artifact: platform-outputs
              displayName: "Download Platform Artifacts"

            - checkout: self

            - task: TerraformInstaller@1
              inputs:
                terraformVersion: latest

            - task: TerraformCLI@2
              displayName: Terraform Init (Databricks)
              inputs:
                command: init
                workingDirectory: $(working_dir)/databricks
                backendType: azurerm
                backendServiceArm: TestV2
                ensureBackend: true
                backendAzureRmResourceGroupName: sttfldatatfstate-rg
                backendAzureRmStorageAccountName: sttfldatatfstate
                backendAzureRmContainerName: sttfldatatfstate-container
                backendAzureRmKey: tfl-data/prod-databricks.tfstate
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: Terraform Plan (Databricks)
              inputs:
                command: plan
                workingDirectory: $(working_dir)/databricks
                commandOptions: '-var-file=../../env/dev/databricks/dev.tfvars -out=tfplan'
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: Terraform Apply (Databricks)
              inputs:
                command: apply
                workingDirectory: $(working_dir)/databricks
                commandOptions: tfplan
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)
