trigger: none

variables:
  - group: variables

stages:
- stage: DatabricksDeploy
  displayName: Deploy Databricks Workspace
  jobs:
  - deployment: DeployDatabricks
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:

            - checkout: self

            - task: TerraformInstaller@1
              displayName: Install Terraform
              inputs:
                terraformVersion: latest

            - task: TerraformCLI@2
              displayName: Terraform Init (Databricks)
              inputs:
                command: init
                workingDirectory: $(working_data_dir)
                backendType: azurerm
                backendServiceArm: TestV2
                ensureBackend: true
                backendAzureRmResourceGroupName: sttfldatatfstate-rg
                backendAzureRmStorageAccountName: sttfldatatfstate
                backendAzureRmContainerName: sttfldatatfstate-container
                backendAzureRmKey: tfl-data/dev-databricks.tfstate
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: Terraform Plan (Databricks)
              inputs:
                command: plan
                workingDirectory: $(working_data_dir)
                commandOptions: >
                  -var-file=../../env/dev/databricks/dev.tfvars
                  -out=tfplan
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: Terraform Apply (Databricks)
              inputs:
                command: apply
                workingDirectory: $(working_data_dir)
                commandOptions: tfplan
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)
