trigger: none

resources:
  pipelines:
    - pipeline: azure-platform-ci
      source: azure-platform-ci
      trigger: 
        branches:
          include:
            - dev
            - uat
            - main 

variables:
  - group: variables
  - name: environment
    value: dev

stages:
# DEV & UAT
- stage: PlatformDeployDevUat
  displayName: "Deploy Platform (Dev/Uat)"
  condition: and(succeeded(), or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranchName'], 'dev'), eq(variables['Build.SourceBranchName'], 'uat')))
  jobs:
  - deployment: ApplyPlatform
    environment: ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: TerraformInstaller@1
              displayName: "Install Terraform"
              inputs:
                terraformVersion: latest

            - task: TerraformCLI@2
              displayName: "Terraform Init"
              inputs:
                command: init
                workingDirectory: $(working_dir)
                backendType: azurerm
                backendServiceArm: TestV2
                ensureBackend: true
                backendAzureRmResourceGroupName: sttfldatatfstate-rg
                backendAzureRmStorageAccountName: sttfldatatfstate
                backendAzureRmContainerName: sttfldatatfstate-container
                backendAzureRmKey: tfl-data/${{ variables.environment }}.tfstate
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: "Terraform Plan"
              inputs:
                command: plan
                workingDirectory: $(working_dir)
                commandOptions: '-var-file=../../env/${{ variables.environment }}/platform/${{ variables.environment }}.tfvars -out=tfplan'
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: "Terraform Apply"
              inputs:
                command: apply
                workingDirectory: $(working_dir)
                commandOptions: tfplan
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: PublishPipelineArtifact@1
              displayName: "Publish Platform Outputs"
              inputs:
                targetPath: $(working_dir)
                artifact: platform-outputs

# PROD
- stage: PlatformDeployProd
  displayName: "Deploy Platform (Prod)"
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
  - deployment: ApplyPlatformProd
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: TerraformInstaller@1
              displayName: "Install Terraform"
              inputs:
                terraformVersion: latest

            - task: TerraformCLI@2
              displayName: "Terraform Init"
              inputs:
                command: init
                workingDirectory: $(working_dir)
                backendType: azurerm
                backendServiceArm: TestV2
                ensureBackend: true
                backendAzureRmResourceGroupName: sttfldatatfstate-rg
                backendAzureRmStorageAccountName: sttfldatatfstate
                backendAzureRmContainerName: sttfldatatfstate-container
                backendAzureRmKey: tfl-data/prod.tfstate
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: "Terraform Plan"
              inputs:
                command: plan
                workingDirectory: $(working_dir)
                commandOptions: '-var-file=../../env/prod/platform/prod.tfvars -out=tfplan'
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)

            - task: TerraformCLI@2
              displayName: "Terraform Apply"
              inputs:
                command: apply
                workingDirectory: $(working_dir)
                commandOptions: tfplan
              env:
                ARM_USE_OIDC: true
                ARM_CLIENT_ID: $(servicePrincipalId)
                ARM_TENANT_ID: $(tenantId)
                ARM_SUBSCRIPTION_ID: $(subscriptionId)
